
version: '3.8'

services:
  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kirill
      - POSTGRES_PASSWORD=kirill
      - POSTGRES_DB=analitic
    ports:
      - "5432:5432"

volumes:
  postgres_data: